hitsTitles = ['BROTHERS IN ARMS','BOHEMIAN RHAPSODY','STAIRWAY TO HEAVEN','RIDERS ON THE STORM','WISH YOU WERE HERE']
hitsTitles.append('CHILD IN TIME')
hitsTitles.append('AGAIN')
print(hitsTitles)
hitsTitles.insert(2,'HOTEL CALIFORNIA')
print(hitsTitles)
print(hitsTitles.index('HOTEL CALIFORNIA'))
hitsTitles.remove('HOTEL CALIFORNIA')
print(hitsTitles)
hitsTitles[0]='ENJOY THE SILENCE'
print(hitsTitles)
hitsToRead = hitsTitles.copy()
print(hitsToRead)
hitsToRead.reverse()
print(hitsToRead)
hitsToRead.sort()
print(hitsToRead)
hitsToRead.pop(0)
hitsToRead.pop(1)
print(hitsToRead)
additionalSongs = ['NOTHING COMPARES 2 U', 'WISH YOU WERE HERE']
hitsToRead.extend(additionalSongs)
print(hitsToRead)
print(hitsToRead.count('NOTHING COMPARES 2 U'))
hitsToRead.clear()
print(hitsToRead)